### PR TITLE
Final features for search, sort, and filter

### PR DESCRIPTION
**Pull request by BENEDIDIN**
This pull request contains all the final code for the search, sort, and filter features. Everything is now linked up to the UI and follows clean architecture. The test has been updated to work with the new flow of control. Cleaned up the code.

### CODE REVIEW

**Review by Dario1031 — DISMISSED** [review]
Great job with getting rid of the dependencies of the original implementation. The UI components for your feature also looks great and functions well. Look into maybe chaning the buttons to match up the style of the other dropdown style menus. Your test coverage looks great, including the new use case test coverage. Great job overall

**Review by bwwaaa — DISMISSED** [review]
Looks great! Your code seems to follow clean architecture consistently and is well documented through your java docs and series of comments within your methods. I would suggest fixing some of your variables, as they are not consistent with the camel case way of naming variables. Overall your code is easy to follow and understand, great job!

**Review by DaneshKohina — APPROVED** [review]
Well done Ben.
Your first implementation was violating the dependency rule, this has now been fixed. In addition, I like your use case test it has great coverage. You have followed clean architecture with your use case, controller, and presenter. In addition SOLID design principles have been followed correctly. Your UI looks great and is functioning well. I like the use of a input boundary interface which gets implemented by the interactor.

**Review by bwwaaa — APPROVED** [review]
Looks great! Your code seems to follow clean architecture consistently and is well documented through your java docs and series of comments within your methods. I would suggest fixing some of your variables, as they are not consistent with the camel case way of naming variables. Overall your code is easy to follow and understand, great job!

**Review by Dario1031 — APPROVED** [review]
Great job with getting rid of the dependencies of the original implementation. The UI components for your feature also looks great and functions well. Look into maybe chaning the buttons to match up the style of the other dropdown style menus. Your test coverage looks great, including the new use case test coverage. Great job overall

**Review by DaneshKohina — APPROVED** [review]
Well done Ben.
Your first implementation was violating the dependency rule, this has now been fixed. In addition, I like your use case test it has great coverage. You have followed clean architecture with your use case, controller, and presenter. In addition SOLID design principles have been followed correctly. Your UI looks great and is functioning well. I like the use of a input boundary interface which gets implemented by the interactor. I approve the new changes (fixes the error).

**Pull request merged**
