### PR TITLE
Final Changes to Inventory Related Components

### PR DESCRIPTION
**Pull request by PeterDushniku**
Final pull request for inventory related components. These includes changes to the inventory entity, Inventory related UI, and the delete inventory use case.

Also, we would like to highlight our use of the dependency injection design pattern. We achieved this by creating InventoryItems and Orders outside of the inventory class as to not hard-code InventoryItems and Orders into Inventory. This way, Orders and Inventory items can be used and tested independently.

### CODE REVIEW

**Review by Dario1031 — DISMISSED** [review]
Hey Peter, your final submission is looking really good. I like the new inventory deletion feature, works well and respects clean architecture. Great job with your use of design patterns, specifically with your dependency injection (creating items and orders outside additem and addorder). Overall your implementation seems to adhere to clean architecture much more than before. Great work.

**Review by DaneshKohina — DISMISSED** [review]
Your final submission is looking really good. I like the inventory deletion feature, it works great and previous errors no loner exist. I like the use of the dependency injection design pattern, by creating items and orders outside additem and addorder. You have adhered to clean architecture and SOLID design principles. Furthermore the testing seems to work well and cover all areas. Well done.

**Review by BENEDIDIN — DISMISSED** [review]
All these changes look good. You have done a very good job with the UI, everything looks nice and is easy and intuitive to use. Changing the sort and filter buttons to menu items was good, as it kept the UI look consistent. The changes to the readMe file are good, as they help the user use the program.

**Review by BENEDIDIN — APPROVED** [review]
All these changes look good. You have done a very good job with the UI, everything looks nice and is easy and intuitive to use. Changing the sort and filter buttons to menu items was good, as it kept the UI look consistent. The changes to the readMe file are good, as they help the user use the program.

**Review by DaneshKohina — APPROVED** [review]
Your final submission is looking really good. I like the inventory deletion feature, it works great and previous errors no loner exist. I like the use of the dependency injection design pattern, by creating items and orders outside additem and addorder. You have adhered to clean architecture and SOLID design principles. Furthermore the testing seems to work well and cover all areas. Well done.

**Review by Dario1031 — APPROVED** [review]
Hey Peter, your final submission is looking really good. I like the new inventory deletion feature, works well and respects clean architecture. Great job with your use of design patterns, specifically with your dependency injection (creating items and orders outside additem and addorder). Overall your implementation seems to adhere to clean architecture much more than before. Great work.

**Pull request merged**
