### PR TITLE
31 6.1 item class

### PR DESCRIPTION
**Pull request by chenbriann**
Added InventoryItem class. Modified Item class. Added barcode generator, to be implemented. Added update item use case, to be implemented. Changed isUnit to isWeight, true if item quantified by weight.

### CODE REVIEW

**Review by DaneshKohina — APPROVED** [review]
Looks good!
I like the changes so far I will update my analysis class for the change of  isUnit to isWeight.
The implementation looks clean and accurate.
The implementation of all the methods I will use are useful to my Analysis class.
Make sure to complete the barcode generator so that then the item class doesn't need to be abstract.
I also suggest creating test cases (this can be done further down the line).

**Comment by bwwaaa** [comment]
Changes are clear and easy to understand, looks great! Creating constructors for inventory items and order items is much more convenient and helpful.

**Review by bwwaaa — APPROVED** [review]
Changes are clear and easy to understand, looks great! Creating constructors for inventory items and order items is much more convenient and helpful.

**Review by BENEDIDIN — APPROVED** [review]
This looks good. I like how you included documentation for the methods that will be accessed by other parts of the code.

**Pull request merged**
