### PR TITLE
Import Basic Functionality

### PR DESCRIPTION
**Pull request by Dario1031**
Added Importer class with appropriate instance variables and methods. Also added an exports folder with a test csv file inside so that functionality can be checked by myself and others.

### CODE REVIEW

**Comment by DaneshKohina** [comment]
I like it.
It seems like you have a good foundation do build the import feature and the example file seems good.
Good Job Dario!

**Review by PeterDushniku — APPROVED** [review]
Approved.

**Review by BENEDIDIN — APPROVED** [review]
This looks good to me.

**Review by DaneshKohina — APPROVED** [review]
I like it.
It seems like you have a good foundation do build the import feature and the example file seems good.
Good Job Dario!

**Pull request merged**
