### PR TITLE
Inventory Created.

### PR DESCRIPTION
**Pull request by PeterDushniku**
Added the Inventory class and some basic instance variables and methods.

### CODE REVIEW

**Review by Dario1031 — APPROVED** [review]
Looks good :)

**Review by guzzim2022 — CHANGES_REQUESTED** [review]
Why is the constructor overloaded three times?

**Review by BENEDIDIN — APPROVED** [review]
This looks like a well made outline of an inventory.

**Review by DaneshKohina — APPROVED** [review]
Looks good I can use it for my Analysis class

**Review by Dario1031 — APPROVED** [review]
Looks good, redundant code removed.

**Review by guzzim2022 — APPROVED** [review]

**Pull request merged**
