### PR TITLE
Created item class.

### PR DESCRIPTION
**Pull request by chenbriann**

### CODE REVIEW

**Review by DaneshKohina — APPROVED** [review]
This Looks good I can use the quantity and price instance variables for my Analysis class.

**Review by Dario1031 — APPROVED** [review]
Structure looks good, everything is clear and concise. Good job!

**Review by BENEDIDIN — APPROVED** [review]
This looks good. All the instance variables will allow me to sort, search, and filter the items in the inventory.

**Review by guzzim2022 — APPROVED** [review]
I approve of this item class. It has all the instance variables that we agreed upon and which will allow us to write the menu system.

**Pull request merged**
