### PR TITLE
Adding Serializable Import and Testing

### PR DESCRIPTION
**Pull request by Dario1031**
Added method to import serializable files and respective test suite . Minor changes made to Exporter.java to make Importer work. Commented out ExportController because it was buggy and not working

### CODE REVIEW

**Review by DaneshKohina — APPROVED** [review]
Great job Dario.
You have begun work on the Controller, make sure to add the Presenter and UI. We are beginning to make progress on Clean Architecture. Make sure to also include SOLID design principles. I suggest to add java docs for each method explaining what it does. You have added a test class that seems to work well. Import and export seem to coincide well.

**Review by BENEDIDIN — APPROVED** [review]
👍

**Review by PeterDushniku — APPROVED** [review]
Looks good.

- Since we are only going to be importing serializable files, the commented out part that would import a csv file is unnecessary at this point. I understand keeping it just in case we decide to change our implementation that the method becomes relevant, but if it is still unused by the end of the project it should be removed completely.
- In the importer tests you can replace items.add(item) with inv1.addItem(item) to make use of that method and use the extra functionality of addItem (checks if the item already exists in the inventory items list).
- Also your test will always pass since Assertions.assertTrue(true) is always true. I see in your TODO comment that you still have to change something about the test structure to make a more relevant test, so that should be figured out soon so we can get some proper testing on the import functionality.

**Review by guzzim2022 — APPROVED** [review]
All is good. thank you for commenting on my code and fixing the small error I had. All your code looks good and it passes all the test and meets expectations

**Pull request merged**
