### PR TITLE
6.2 item management system

### PR DESCRIPTION
**Pull request by chenbriann**
This PR contains major implementation of the barcode functionality of the Item class, notably barcode reading, generating, writing and removing. It also includes test cases for these functionalities, JavaDocs detailing public classes and methods as well as numerous comments for readability. The code somewhat adheres to SOLID principles and clean architecture, but will need to be refactored in a future PR when the interface adapters and UI are implemented.

### CODE REVIEW

**Comment by chenbriann** [comment]
Ignore main I left a bunch of test code there.

**Review by Dario1031 — APPROVED** [review]
The code in this pull request overall looks very well done. I like the added form of data persistence (adhering to clean architecture) with the barcodes being stored/removed from a .csv file.  The sheer volume of code in this pr is really overwhelming and it obscures the function of your code a bit, but it is well commented and equally thoroughly tested. The UpdateItemQuantity use case is also a good example of clean architecture and package organization. Going forward I believe there are a few minor changes to be made to adhere more to SOLID and clean architecture but this is an awesome start.

**Review by BENEDIDIN — APPROVED** [review]
One thing I would change in this code is to break up some of the longer methods, specifically generateBarcode, since long methods aren't CLEAN architecture. Also I don't really understand what the point of using a file is in generateBarcode. I also don't really understand why barcode is a string and not an int. Finally, I am concerned about how generate barcode works with items of the same name, as I think two items of the same name should have the same barcode but the way generateBarcode works it won't do that.

**Review by DaneshKohina — APPROVED** [review]
Well Done Brian.
You have included data persistence as the barcodes are stored and removed from a CSV file. You have included a lot of code in one pull request, I would prefer if next time you could do it in stages as then our reviews will be less error prone. You have included package organization into your implementation. I think we need to focus on adding some SOLID design principles to this code.

**Pull request merged**
